# Checkov configuration for Lex Platform
# https://www.checkov.io/2.Basics/Suppressing%20and%20Skipping%20Policies.html

skip-check:
  - CKV_AWS_117
  - CKV_AWS_173

soft-fail: false

framework:
  - terraform

output:
  - sarif

skip-path:
  - .terraform/
  - .git/
